# Generated by Django 2.0.8 on 2018-09-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=30)),
                ('last_name', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.CharField(blank=True, default='', max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6)),
                ('age', models.IntegerField(blank=True, default=0)),
                ('paddling_experience', models.IntegerField(blank=True, default=0)),
                ('paddling_preference', models.CharField(choices=[('none', 'None'), ('left', 'Left'), ('right', 'Right'), ('drummer', 'Drummer'), ('cox', 'Cox')], default='none', max_length=7)),
                ('previous_teams', models.TextField(blank=True, default='')),
                ('weight', models.CharField(blank=True, default='', max_length=10)),
                ('height', models.CharField(blank=True, default='', max_length=10)),
                ('max_bench_press', models.CharField(blank=True, default='', max_length=10)),
                ('max_number_chinups', models.CharField(blank=True, default='', max_length=10)),
                ('five_km_jog_time', models.CharField(blank=True, default='', max_length=10)),
                ('comments', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
