# Generated by Django 2.0.8 on 2018-09-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_emailforward'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
