# Generated by Django 2.0.8 on 2018-09-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_about_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='news_images', verbose_name='image')),
                ('body', models.TextField(default='')),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
