# Generated by Django 2.0.8 on 2018-09-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_initial', models.CharField(max_length=1)),
                ('image', models.ImageField(upload_to='profile_images', verbose_name='image')),
                ('status', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='right', max_length=5)),
                ('active', models.BooleanField(default=True)),
                ('captain', models.BooleanField(default=False)),
                ('coach', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
