# Generated by Django 2.0.8 on 2018-09-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='status',
            new_name='paddle',
        ),
    ]
