# Generated by Django 2.0.8 on 2018-09-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_paddle_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='joined',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='paddle',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], max_length=5, null=True),
        ),
    ]
