# Generated by Django 2.0.8 on 2019-01-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_profile_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Join Description',
                'verbose_name_plural': 'Join Description',
            },
        ),
    ]
