# Generated by Django 2.0.8 on 2019-01-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_albums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
